[package]
name = "socket_trench"
version = "1.0.0"
edition = "2021"

[dependencies]
libadwaita = { version = "0.4.4", features = ["v1_4"] }
relm4 = { version = "0.6.2", features = ["libadwaita"] }
relm4-components = "0.6.2"
sys-locale = "0.3.1"
rust-i18n = "3.0.1"