[package]
name = "socket_trench"
version = "1.0.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
gtk4 = "0.9.0"
libadwaita = { version = "0.7.0", features = ["v1_4"] }
